/*
 * $QNXLicenseC:
 * Copyright 2010, QNX Software Systems.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You
 * may not reproduce, modify or distribute this software except in
 * compliance with the License. You may obtain a copy of the License
 * at: http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OF ANY KIND, either express or implied.
 *
 * This file may contain contributions from others, either as
 * contributors under the License or as licensors under other terms.
 * Please review this entire file for other proprietary rights or license
 * notices, as well as the QNX Development Suite License Guide at
 * http://licensing.qnx.com/license-guide/ for other information.
 * $
 */

#include <startup.h>
#include "omap4430_padconf.h"
#include "omap4430.h"


pin_cfg_t     early_pin_config[] = {

};

unsigned    early_pin_config_size = sizeof(early_pin_config)/sizeof(early_pin_config[0]);

pin_cfg_t     pin_config[] = {

  /* MMC1 CLK */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_USBC1_ICUSB_DM_PAD1_SDMMC1_CLK,
    .func= FuncId_SDMMC1_CLK,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MMC1 CMD */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC1_CMD_PAD1_SDMMC1_DAT0,
    .func= FuncId_SDMMC1_CMD,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MMC1 DAT0 */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC1_CMD_PAD1_SDMMC1_DAT0,
    .func= FuncId_SDMMC1_DAT0,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MMC1 DAT1 */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC1_DAT1_PAD1_SDMMC1_DAT2,
    .func= FuncId_SDMMC1_DAT1,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MMC1 DAT2 */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC1_DAT1_PAD1_SDMMC1_DAT2,
    .func= FuncId_SDMMC1_DAT2,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MMC1 DAT3 */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC1_DAT3_PAD1_SDMMC1_DAT4,
    .func= FuncId_SDMMC1_DAT3,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MMC1 DAT4 */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC1_DAT3_PAD1_SDMMC1_DAT4,
    .func= FuncId_SDMMC1_DAT4,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MMC1 DAT5 */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC1_DAT5_PAD1_SDMMC1_DAT6,
    .func= FuncId_SDMMC1_DAT5,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MMC1 DAT6 */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC1_DAT5_PAD1_SDMMC1_DAT6,
    .func= FuncId_SDMMC1_DAT6,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MMC1 DAT7 */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC1_DAT7_PAD1_ABE_MCBSP2_CLKX,
    .func= FuncId_SDMMC1_DAT7,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },

  /* MCSPI1_CLK */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_I2C4_SDA_PAD1_MCSPI1_CLK,
    .func= FuncId_MCSPI1_CLK,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MCSPI1_SOMI */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_MCSPI1_SOMI_PAD1_MCSPI1_SIMO,
    .func= FuncId_MCSPI1_SOMI,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MCSPI1_SIMO */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_MCSPI1_SOMI_PAD1_MCSPI1_SIMO,
    .func= FuncId_MCSPI1_SIMO,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MCSPI1_CS0 */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_MCSPI1_CS0_PAD1_MCSPI1_CS1,
    .func= FuncId_MCSPI1_CS0,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MCSPI1_CS1 as GPIO 138 as output */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_MCSPI1_CS0_PAD1_MCSPI1_CS1,
    .func= FuncId_GPIO_138,
    .options=(PADCONF_INPUTENABLE_NOINPUT | PADCONF_PULLUDENABLE_DISABLE) },
  /* GPIO 43 as output, to enable wireless LAN on TiWi01 wireless module*/  { .pad= PADCONF_PAD1,    .reg= OMAP44XX_CONTROL_CORE_PAD0_GPMC_A18_PAD1_GPMC_A19,    .func= FuncId_GPIO_43,    .options=(PADCONF_INPUTENABLE_NOINPUT | PADCONF_PULLUDENABLE_DISABLE) },
  /* GPIO 48 as output, to power ethernet */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_GPMC_A24_PAD1_GPMC_A25,
    .func= FuncId_GPIO_48,
    .options=(PADCONF_INPUTENABLE_NOINPUT | PADCONF_PULLUDENABLE_DISABLE) },

  /* GPIO 53 */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_GPMC_NCS2_PAD1_GPMC_NCS3,
    .func= FuncId_GPIO_53,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* GPIO 54 */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_GPMC_NWP_PAD1_GPMC_CLK,
    .func= FuncId_GPIO_54,
    .options=(PADCONF_INPUTENABLE_NOINPUT | PADCONF_PULLUDENABLE_DISABLE) },
  /* GPIO 46 (BT_EN) */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_GPMC_A22_PAD1_GPMC_A23,
    .func= FuncId_GPIO_46,
    .options=(PADCONF_INPUTENABLE_NOINPUT | PADCONF_PULLUDENABLE_DISABLE) },
  /* MMCSD5 CLK */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC5_CLK_PAD1_SDMMC5_CMD,
    .func= FuncId_SDMMC5_CLK,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MMCSD5 CMD */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC5_CLK_PAD1_SDMMC5_CMD,
    .func= FuncId_SDMMC5_CMD,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MMCSD5 DAT0 */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC5_DAT0_PAD1_SDMMC5_DAT1,
    .func= FuncId_SDMMC5_DAT0,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MMCSD5 DAT1 */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC5_DAT0_PAD1_SDMMC5_DAT1,
    .func= FuncId_SDMMC5_DAT1,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MMCSD5 DAT2 */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC5_DAT2_PAD1_SDMMC5_DAT3,
    .func= FuncId_SDMMC5_DAT2,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* MMCSD5 DAT3 */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_SDMMC5_DAT2_PAD1_SDMMC5_DAT3,
    .func= FuncId_SDMMC5_DAT3,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* HDMI DDC SCL */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_GPIO65_PAD1_GPIO66,
    .func= FuncId_HDMI_DDC_SCL,
    .options=(PADCONF_INPUTENABLE_INPUT) },
  /* HDMI DDC SDA */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_GPIO65_PAD1_GPIO66,
    .func= FuncId_HDMI_DDC_SDA,
    .options=(PADCONF_INPUTENABLE_INPUT) },
  /* GPIO34 (ENET_IRQ) */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_GPMC_AD10_PAD1_GPMC_AD11,
    .func= FuncId_GPIO_34,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* GPIO37 (CAM_PDN_A) */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_GPMC_AD12_PAD1_GPMC_AD13,
    .func= FuncId_GPIO_37,
    .options=(0) },
  /* GPIO39 (MTOUCH_IRQ) as input, pull-up in default */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_GPMC_AD14_PAD1_GPMC_AD15,
    .func= FuncId_GPIO_39,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
  /* GPIO83 (CAM_GLB_nRST) */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_CAM_GLOBALRESET_PAD1_USBB1_ULPITLL_CLK,
    .func= FuncId_GPIO_83,
    .options=(0) },
  /* GPIO102 (LVDS_RST#) */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_GPMC_NCS4_PAD1_GPMC_NCS5,
    .func= FuncId_GPIO_102,
    .options=(0) },
  /* FREF_CLK1_OUT */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_USBA0_OTG_DM_PAD1_FREF_CLK1_OUT,
    .func= FuncId_FREF_CLK1_OUT,
    .options=(0) },

  /* MCSPI4_CLK */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_MCSPI4_CLK_PAD1_MCSPI4_SIMO,
    .func= FuncId_MCSPI4_CLK,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_OFFMODEENABLE_FORCEOFF | PADCONF_OFFMODEPULLUDENABLE_ENABLE | PADCONF_OFFMODEOUTENABLE_DISABLE) },
  /* MCSPI4_SOMI */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_MCSPI4_SOMI_PAD1_MCSPI4_CS0,
    .func= FuncId_MCSPI4_SOMI,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_OFFMODEENABLE_FORCEOFF | PADCONF_OFFMODEPULLUDENABLE_ENABLE | PADCONF_OFFMODEOUTENABLE_DISABLE) },
  /* MCSPI4_SIMO */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_MCSPI4_CLK_PAD1_MCSPI4_SIMO,
    .func= FuncId_MCSPI4_SIMO,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_OFFMODEENABLE_FORCEOFF | PADCONF_OFFMODEPULLUDENABLE_ENABLE | PADCONF_OFFMODEOUTENABLE_DISABLE) },
  /* MCSPI4_CS0 */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_MCSPI4_SOMI_PAD1_MCSPI4_CS0,
    .func= FuncId_MCSPI4_CS0,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLDN | PADCONF_OFFMODEENABLE_FORCEOFF | PADCONF_OFFMODEPULLUDENABLE_ENABLE | PADCONF_OFFMODEOUTENABLE_DISABLE) },

  /* FREF_CLK1_OUT */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_USBA0_OTG_DM_PAD1_FREF_CLK1_OUT,
    .func= FuncId_FREF_CLK1_OUT,
    .options=(0) },
  /* McBSP1_CLKX */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_ABE_MCBSP2_FSX_PAD1_ABE_MCBSP1_CLKX,
    .func= FuncId_ABE_MCBSP1_CLKX,
    .options=(PADCONF_INPUTENABLE_INPUT) },
  /* McBSP1_DX */
  { .pad= PADCONF_PAD1,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_ABE_MCBSP1_DR_PAD1_ABE_MCBSP1_DX,
    .func= FuncId_ABE_MCBSP1_DX,
    .options=(0) },
  /* McBSP1_DR */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_ABE_MCBSP1_DR_PAD1_ABE_MCBSP1_DX,
    .func= FuncId_ABE_MCBSP1_DR,
    .options=(PADCONF_PULLUDENABLE_ENABLE|PADCONF_INPUTENABLE_INPUT|PADCONF_OFFMODEPULLUDENABLE_ENABLE) },
  /* McBSP1_FSX */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_CORE_PAD0_ABE_MCBSP1_FSX_PAD1_ABE_PDM_UL_DATA,
    .func= FuncId_ABE_MCBSP1_FSX,
    .options=(PADCONF_INPUTENABLE_INPUT) },

};

unsigned    pin_config_size = sizeof(pin_config)/sizeof(pin_config[0]);


pin_cfg_t     wkup_pin_config[] = {

#if 1 /* NOTE: THIS WILL ONLY WORK IF NOT SECURITY IS NOT PREVENTING ACCESS PAD CONFIG! */
  /* Force MSECURE TO BE DISABLE FOR RTC access on PMIC */
  { .pad= PADCONF_PAD0,
    .reg= OMAP44XX_CONTROL_WKUP_PAD0_FREF_CLK0_OUT_PAD1_FREF_CLK3_REQ,
    .func= FuncId_GPIO_WK6,
    .options=(PADCONF_INPUTENABLE_INPUT | PADCONF_PULLUDENABLE_ENABLE | PADCONF_PULLTYPESELECT_PULLUP) },
#endif
};

unsigned    wkup_pin_config_size = sizeof(wkup_pin_config)/sizeof(wkup_pin_config[0]);

pin_cfg_t     late_pin_config[] = {

};

unsigned    late_pin_config_size = sizeof(late_pin_config)/sizeof(late_pin_config[0]);

#if defined(__QNXNTO__) && defined(__USESRCVERSION)
#include <sys/srcversion.h>
__SRCVERSION("$URL: http://svn/product/branches/6.6.0/trunk/hardware/startup/boards/omap4430/panda/io_cfg.c $ $Rev: 735852 $")
#endif
