ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

define PINFO
PINFO DESCRIPTION=Synaptics Touch Driver
endef

CCFLAGS	+=-D_FILE_OFFSET_BITS=32 -D_IOFUNC_OFFSET_BITS=32 -D_LARGEFILE64_SOURCE=0
LDFLAGS += -M

NAME=$(PROJECT)
USEFILE=


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

